### PR TITLE
[LANG-CHANGE] Update precedence rules, flattening the precedence hier…

### PR DESCRIPTION
**Pull request by lerno**
…archy and increasing precedence of bitwise operators.

I did the (almost) simplest possible change here, adding () in as simple way as possible. A nicer solution would have been to actually check if the parent expression already was surrounded by () when printing to C.

Note that I haven't looked at anything but the AST and the C output. There might be subtle things that I have overlooked. Testcases are updated and a new test case for some of operators have been added.

### CODE REVIEW

**Comment by bvdberg** [comment]
This is a pretty big change (not codewise, but language wise). Could you perhaps show the consequences by some examples?

**Comment by bvdberg** [comment]
The patch itself looks in good shape. I only want to merge it when I've also updated the documenation..

**Comment by lerno** [comment]
@bvdberg how should I send the examples? Write here? The forum? Wiki?

**Comment by bvdberg** [comment]
I think the best way would be to change the documentation (in c2lang/docs
from head)...or else just write them in email and I'll convert to doc site

**Comment by lerno** [comment]
I added to the wiki now @bvdberg

**Comment by bvdberg** [comment]
I've given the Wiki and c2lang.org/docs/ an update. I've also restricted the Wiki access. Apparently the default on github is that everyone can edit.

**Pull request merged**
